#############################################
###     Makefile du code écrit par:       ###
###           Guillaume Renaud            ###
###         Loic Bellmare-Alford          ###
###           Julien Bergeron             ###
###         Yann-Joel D. Tessier          ###
###                                       ###
###           Équipe 08-89                ###
###          INF1995 - 2017               ###
#############################################

#
CPP=tp8.cpp
PROJECTNAME=optimusprime
LIBS=-L ../lib_dir -l89
TRG=$(PROJECTNAME).out
TRG_CMD=$(CC) $(LDFLAGS) -o $(TRG) $(OBJDEPS) \
	-lm $(LIBS)
INCL=$(INC)
-include ../Makefile.common
