#############################################
###  Makefile de la librairie écrit par:  ###
###           Guillaume Renaud            ###
###         Loic Bellmare-Alford          ###
###           Julien Bergeron             ###
###         Yann-Joel D. Tessier          ###
###                                       ###
###           Équipe 08-89                ###
###          INF1995 - 2017               ###
#############################################

# Les fichiers contenant les fonctionnalités
CPP=pwm.cpp

#Le nom de la librairie
PROJECTNAME=lib89

INC=-I ../include
AR=avr-ar crs
TRG=$(PROJECTNAME).a
TRG_CMD=$(AR) $(TRG) $(OBJDEPS)
C=-c
-include ../Makefile.common
